version: "2"
networks:
  rot:

services:
  orderer.rot.com:
    container_name: orderer.rot.com
    image: hyperledger/fabric-orderer:1.4.3
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug #로그메시지 표시 수준 설정
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 #orderer의 주소 값
      - ORDERER_GENERAL_GENESISMETHOD=file #제네시스 블록을 지정하는 방법
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block #제네시스 블록 경로
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg #해당 orderer의 Loacl MSP ID
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp #해당 orderer의 Local MSP 경로
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/rot.com/orderers/orderer.rot.com/:/etc/hyperledger/msp/orderer
    networks:
      - rot

  peer0.estate1.rot.com:
    container_name: peer0.estate1.rot.com
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock #Docker 데몬 주소
      - CORE_PEER_ID=peer0.estate1.rot.com #peer를 식별하는 ID
      - CORE_LOGGING_PEER=debug #로그 메시지 표시 수준 설정
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Estate1Org #해당 peer의 Local MSP ID
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/ #해당 peer의 Local MSP 경로
      - CORE_PEER_ADDRESS=peer0.estate1.rot.com:7051 #peer의 주소 값
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.estate1.rot.com:7051 #앵커 peer의 endpoint 및 주소.
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.estate1.rot.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.estate1.rot.com:7051 #peer에서 발생하는 모든 외부 통신에 대한 endpoint 또는 주소
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_rot
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/estate1.rot.com/peers/peer0.estate1.rot.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/estate1.rot.com/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.rot.com
    networks:
      - rot

  peer1.estate1.rot.com:
    container_name: peer1.estate1.rot.com
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.estate1.rot.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Estate1Org
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.estate1.rot.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_rot
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:8051
      - 8053:8053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/estate1.rot.com/peers/peer1.estate1.rot.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/estate1.rot.com/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.rot.com
    networks:
      - rot

  peer0.estate2.rot.com:
    container_name: peer0.estate2.rot.com
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.estate2.rot.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Estate2Org
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.estate2.rot.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_rot
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 9051:9051
      - 9053:9053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/estate2.rot.com/peers/peer0.estate2.rot.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/estate2.rot.com/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.rot.com
    networks:
      - rot

  peer1.estate2.rot.com:
    container_name: peer1.estate2.rot.com
    image: hyperledger/fabric-peer:1.4.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.estate2.rot.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Estate2Org
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.estate2.rot.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_rot
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 10051:10051
      - 10053:10053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/estate2.rot.com/peers/peer1.estate2.rot.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/estate2.rot.com/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.rot.com
    networks:
      - rot

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.estate1.rot.com:7051
      - CORE_PEER_LOCALMSPID=Estate1Org
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/estate1.rot.com/users/Admin@estate1.rot.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./config:/etc/hyperledger/configtx
    networks:
      - rot
